# bio
**The bioinformatics project**: Inferring the infection pathway of influenza

2018 SFU Invent the Future

In this project, students will learn how computational biology can allow us to predict future strains of viruses, in order to preventatively make vaccines before outbreaks occur. 

Phylogenetic trees are widely used in biology to represent evolutionary relationships between species, such as how wolves are related to domesticated dogs. In these trees, leaves represent currently living species, and the internal branches indicate speciation events, where new species were thought to be created. The overall structure and shape of a phylogenetic tree reveals useful information such as the rate of new species formation and extinction. Tree balance usually refers to the structure of the tree, and branch lengths show the time or genetic distance between branching or speciation events.

Phylogenetic trees can also be used to extract information from viral/bacterial/vector speciation events generated by disease outbreaks. This information can be used to analyze the rate and patterns of how new species of virus/bacteria/vectors evolve, providing valuable information towards the development of vaccinations and preventative measures.

Homepage: https://sites.google.com/view/ai4all-sfu2018/projects/bioinformatics

Github repository: https://github.com/ai4all-sfu/bio

Slides: https://docs.google.com/presentation/d/1XpPjTZGQP1KkpAeiDjAUfz-uCqQMs2x1_a4lo_aJa3o/edit?usp=sharing


## usage

1. install mafft (for multiple sequence alignment) @ [https://mafft.cbrc.jp/alignment/software/](https://mafft.cbrc.jp/alignment/software/)

2. download this repository and follow the R code in **[main.html](main.html)**; remember to **change the variable "root"** to the local folder you downloaded this repository to, and if you are starting anew, **set "result\_time\_="""**

## folder/file structure

code, ran in the following order
- [prep_linux.Rmd](prep_linux.Rmd): only for linux users; installs necessary system packages
- [prep_data.R](prep_data.R): preprocess data
- [main.Rmd](main.Rmd): main curriculum; html render [main.html](main.html)

data_ folder contains original data (not to be modified)
- FASTA.fa: viral strain sequences
- meta\_\<database\>: metadata from different databases; ncbi has country and all strains, fludb has country & state and some strains

data folder contains processed data (FASTA.fa, meta.csv are outputs of [prep_data.R](prep_data.R); alignment.fa is an output of [main.Rmd](main.Rmd))
- FASTA.fa: the HA gene sequence in influenza subtype A/H3N2 from years 1997 - 2017 (sorted by date) (n = 10370)
- meta.csv: metadata merged, and sorted by date the same way as FASTA.fa 
- alignment.fa: viral strain sequence alignments of mafft made using FASTA.fa 
- Aux_data.csv: contains all the strain name and date from FASTA.fa
- FinalH3N2: maximum likelihood generated phylogeny made from FASTA.fa
- df.csv: features for each strain/clade used for prediction

result/\<date\>\_\<time\> folder contains results separated by time of making (output of [main.Rmd](main.Rmd))
- ind.csv: randomly sampled strain names of 200 recent viral sequences
- FASTA\_anc.fa: reconstructed ancestral sequences
- FASTA\_all.fa: data/FASTA.fa (minus the 200 sequences) + reconstructed ancestral sequences
- alignment\_anc.fa: alignment of sequences in FASTA\_all.fa
- dm\_anc.Rdata: distance matrix made using alignment\_anc.fa







